; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:SmartHandController]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = 
	~/Arduino/libraries
	~/Nextcloud/Workspace/ARDUINO/00_LIB
lib_deps = olikraus/U8g2@^2.34.22  ; orig 15
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = huge_app.csv
; upload_speed = 921600
upload_speed = 115200 
; Powershell: usbipd list
;             usbipd attach --busid <busid>
; upload_port = /dev/ttyUSB0 ; MAC/LINUX
upload_port = /dev/cu.usbserial-10
; upload_port = COM3 ; Windows


[platformio]
description = Smart Hand Controller